### ISSUE TITLE
Questions about input file sequence

### ISSUE THREAD

**Issue by Tang-pro** [heche-psb/wgd#25]
Hi, @heche-psb 

When using WGD analysis, can I use the protein sequence directly? Because the full-length transcriptome I constructed currently does not have a cds sequence. Is there any solution?

**Comment by heche-psb** [comment]
Hi, thanks for your interest in using `wgd v2`. So far all the analysis in `wgd v2` are based on nucleotide sequence (cds). For `wgd ksd`, it's because we used the codon-level nucleotide alignment for gene tree inference and of course becuase it's needed for the calculation of `dS` and `dN`. But for `wgd dmd`, it's indeed possible to just use protein sequence. I will update functions to accept protein sequences later. Thanks for your suggestion.

**Comment by Tang-pro** [comment]
@heche-psb , Thank you for your reply, looking forward to your updates!

**Comment by heche-psb** [comment]
Hi, I have just updated the `--prot` option into `wgd dmd`. Please install the latest version `2.0.28` to try it.

**Comment by Tang-pro** [comment]
Hi , @heche-psb 

That is so quick I will try. Thank you!
Best!
