### ISSUE TITLE
ksd .tsv out

### ISSUE THREAD

**Issue by ilaydagulmez** [heche-psb/wgd#34]
Hi, thanks for the great tool!

I have a problem with .tsv file. Tool and command were successfully run and I got the plots. But when I tried the "peak" command, got the error. Then when I looked at my .tsv file there was no numeric counts:

<img width="1440" alt="Ekran Resmi 2024-05-21 09 48 23" src="https://github.com/heche-psb/wgd/assets/163100594/ce29c144-d0ed-4b7f-b560-bb12d7046139">

Here is my input file looks like:

<img width="1440" alt="Ekran Resmi 2024-05-21 09 48 56" src="https://github.com/heche-psb/wgd/assets/163100594/5720ae18-c7df-4154-9397-6cf97add11c1">

dmd command output:
<img width="1440" alt="Ekran Resmi 2024-05-21 09 49 39" src="https://github.com/heche-psb/wgd/assets/163100594/4bcc5405-67f3-4821-b350-6558dca9c947">

Thanks for your time,

İlayda

**Comment by heche-psb** [comment]
Hi, thanks for your interest in using `wgd v2`! The `NaN` is a result of stripped alignment length as 0 for that family (i.e., after removing all gap-containing columns) because `codeml` will drop all gap-containing columns. This is often observed for big families, say, families with >200 gene members. If you want to get the Ks values for those families with stripped alignment length as 0 anyhow, you may add the `--pairwise` option which calculates the Ks in a pairwised fashion by subsetting the corresponding pairwise alignment from the whole familiy alightment, which is usually less gappy and thus Ks-calculatable. Could you please share  the log and command information for your usage of `wgd peak`? I need a bit more details so as to look into it.

**Comment by ilaydagulmez** [comment]
Hi, thanks for your quick response. 

I will try with the --pairwise option immediately, then with this out, try again wgd peak. If there is still an error I will add a log file and other details. 

Thank you so much!

**Comment by ilaydagulmez** [comment]
Hi again! I tried with the command `--pairwise` but it doesn't work. Here is the fail log:

"IndexError: list index out of range"

<img width="920" alt="Screenshot 2024-05-24 at 08 45 18" src="https://github.com/heche-psb/wgd/assets/163100594/ddea3ea8-919b-485f-804c-d7760576552e">

Thanks for your time.

**Comment by heche-psb** [comment]
Hi, which family went error? Could you please share me with the cds and family file of those problematic families, I will try to reproduce your error.

**Comment by ilaydagulmez** [comment]
Hi, thanks for your quick response. Here are my files:

CDS file: 
[cds.fasta.gz](https://github.com/heche-psb/wgd/files/15429428/cds.fasta.gz)


family: 
[cds.fasta.txt](https://github.com/heche-psb/wgd/files/15429412/cds.fasta.txt)

log: [slurm-1684903.out.txt](https://github.com/heche-psb/wgd/files/15429435/slurm-1684903.out.txt)

**Comment by heche-psb** [comment]
Hi, please first install the `v2.0.38` and try again. There might be some bugs in the older versions which I have fixed already in the latest version.

**Comment by ilaydagulmez** [comment]
Hi, I didn't see the update sorry, thanks! I will try immediately.

**Comment by ilaydagulmez** [comment]
Hi again, 

I used to try the latest version, and `dmd` succeeded but `ksd` wasn't with the parameter `--pairwise`. Here is the log:
<img width="912" alt="Screenshot 2024-05-27 at 09 05 55" src="https://github.com/heche-psb/wgd/assets/163100594/d884a3c4-e5af-4377-8a3c-b7c68f99b1f5">

When I run the without` --pairwise` it's completed but as I wrote before, I want to run` --peak` and `--focus` so with `NaN` values, it doesn't work.

The main problem is the time limit now, 3 days will not be enough for `--pairwise` but our server works max. 3 days.

Thank you for your time!
